[package]
name = "codecrafters-grep"
version = "0.1.0"
authors = ["Tudor Andrei Dicu <tudor.andrei.dicu@gmail.com>"]
edition = "2021"
rust-version = "1.80"

[dependencies]
bitflags = "2.6"
anyhow = "1.0"
